POST http://localhost:3000/api/register
Content-Type: application/json

{
    "username": "sebas3",
    "password": "pass"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "sebas3425",
    "password": "passsss"
}