POST http://localhost:3000/api/register
Content-Type: application/json

{
    "username": "sebas3",
    "password": "pass"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "sebas3",
    "password": "pass"
}

###
GET http://localhost:3000/api/restaurants
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlYmFzMyIsImlhdCI6MTY2Mjg1NDA4MiwiZXhwIjoxNjYyODYxMjgyfQ.5AlAqQ7eN5DDGnkJuDiy7k4iF3NSEP-cxacQw7B0na4
Content-Type: application/json

{
    "city": "Pereira"
}

###
GET http://localhost:3000/api/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlYmFzMyIsImlhdCI6MTY2Mjg1NDA4MiwiZXhwIjoxNjYyODYxMjgyfQ.5AlAqQ7eN5DDGnkJuDiy7k4iF3NSEP-cxacQw7B0na4